// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_decodepl
DataFrame rcpp_decodepl(std::string encoded);
RcppExport SEXP googleway_rcpp_decodepl(SEXP encodedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type encoded(encodedSEXP);
    __result = Rcpp::wrap(rcpp_decodepl(encoded));
    return __result;
END_RCPP
}
