# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_polygon_geojson <- function(data, params, geometry_columns) {
    .Call(`_googleway_rcpp_polygon_geojson`, data, params, geometry_columns)
}

rcpp_polygon_polyline <- function(data, params, geometry_columns) {
    .Call(`_googleway_rcpp_polygon_polyline`, data, params, geometry_columns)
}

