# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_decode_pl <- function(encoded) {
    .Call('googleway_rcpp_decode_pl', PACKAGE = 'googleway', encoded)
}

EncodeCoordinates <- function(latitude, longitude, num_coords) {
    .Call('googleway_EncodeCoordinates', PACKAGE = 'googleway', latitude, longitude, num_coords)
}

